esphome:
  name: relay-4ch
  friendly_name: Relay-4Ch

esp32:
  board: esp32dev
  framework:
    type: arduino
    
    
    

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "your_key"

ota:
  - platform: esphome
    password: "your_api_password"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Relay-4Ch Fallback Hotspot"
    password: "password"

captive_portal:


output:
  - platform: gpio
    pin: GPIO23
    id: led
  - platform: gpio
    pin: GPIO1
    id: led_1
  - platform: gpio
    pin: GPIO5
    id: led_2
  - platform: gpio
    pin: GPIO9
    id: led_3

# Define the switches based on the relay pins
switch:
  - platform: gpio
    pin: GPIO32
    id: relay1
    name: "Relay1"

  - platform: gpio
    pin: GPIO33
    id: relay2
    name: "Relay2"

  - platform: gpio
    pin: GPIO25
    id: relay3
    name: "Relay3"

  - platform: gpio
    pin: GPIO26
    id: relay4
    name: "Relay4"

interval:
  - interval: 1000ms
    then:
      - output.turn_on: led
      - delay: 500ms
      - output.turn_off: led
